services:
  app:
    build: .
    networks:
      phish-network:
    volumes:
      - app:/app
    restart: on-failure
    depends_on:
      - db
 
  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - nginx-log:/var/log/nginx
    networks:
      phish-network:
    ports:
      - "80:80" 

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_USER: phisher
      POSTGRES_DB: phisher

    networks:
      - phish-network
    # ports:
    #   - "5432:5432"


networks:
  phish-network:
    
volumes:
  nginx:
  nginx-log:
  app: