# Generated by Django 5.1.2 on 2024-10-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_a', models.CharField(max_length=255)),
                ('opt_b', models.CharField(max_length=255)),
                ('opt_c', models.CharField(max_length=255)),
                ('opt_d', models.CharField(max_length=255)),
                ('true_opt', models.CharField(max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
