# Generated by Django 5.1.2 on 2024-10-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_remove_target_first_name_remove_target_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='target',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
