# Generated by Django 5.1.2 on 2024-10-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_target_first_name_target_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='last_name',
        ),
    ]
